baseURL = "https://www.profzabot.com.br/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Prof. Zabot"
theme = "profzabot-custom"

[outputs]
  home = ["HTML"]

[params]
  description = "Doutor em Astrofísica · Professor da UFSC"
  ogImage = "/images/sobre/eu.jpg"
  author = "Prof. Alexandre Zabot"
  ga_id = "G-YY0YJ7HRDS"
